let toolsData = [
    {
        name: "Spade",
        imageUrl: "/static/images/FarmingTools/spade.jpg",
        description: "A spade is a tool primarily for digging consisting of a long handle and blade, typically with the blade narrower and flatter than the common shovel. With a metal tip, a spade can both break and move the earth in most situations, increasing efficiency. A classic spade, with a narrow body and flat (or near flat) tip is suited for digging post holes, and is not to be confused with a \"roundpoint\" shovel, which has a wider body and tapered tip. People often mistakenly use the word shovel interchangeably with spade but shovel is a generic term for a variety of tools that include numerous broad-bottomed versions for moving loose materials, such as a \"coal shovel\", \"snow shovel\", \"grain shovel\", etc., whereas spades tend to have a sharpened edge, curved profile, and pointed end better designed for digging. Noting that the term \"garden spade\" is attached to certain sharp-edged but square ended tools suited to cutting through sod. The most common garden spade typically has a long handle, is wide, and has rests for the feet to drive the spade into the ground"
    },
    {
        name: "Plough",
        imageUrl: "/static/images/FarmingTools/plough.jpg",
        description: "A plough is a farm tool for loosening or turning the soil before sowing seed or planting. Ploughs were traditionally drawn by oxen and horses, but in modern farms are drawn by tractors. A plough may have a wooden, iron or steel frame, with a blade attached to cut and loosen the soil. The prime purpose of ploughing is to turn over the uppermost soil, bringing fresh nutrients to the surface while burying weeds and crop remains to decay. Trenches cut by the plough are called furrows. In modern use, a ploughed field is normally left to dry and then harrowed before planting. Ploughing and cultivating soil evens the content of the upper 12 to 25 centimetres (5 to 10 inches) layer of soil, where most plant-feeder roots grow. Mouldboard plough: This is made of carbon steel or steel alloy, the base of which is at the right angle triangle. The size of the mouldboard plough is measured by the width of the furrow that is opened by the plough. Generally, it can open a furrow of about 20 cm and above. It throws the furrow slices only on one side. Disc plough: It consists of moving circular steel discs of varying sizes. The size of discs includes its diameter and thickness. Discs in different ploughs used are 50–90 cm in diameter. Discs cut, turn and break furrow slices. These can work well in sticky soil, as well as, in very hard and dry soil. It is much heavier and leaves the soil rough and cloddy. Sub-soil single arm plough (Patashi plough): This plough is useful for heavy soils. It consists of a single adjustable arm having shears at the base and breaks the hard pan developed below the soil surface. It improves drainage in water stagnant soils. It can be inserted up to 50 cm deep in the soil and is most suitable for making a trench of 5–7 cm wide."
    },
    {
        name: "Harrow",
        imageUrl: "/static/images/FarmingTools/harrow.jpg",
        description: "A harrow is a farm implement used for surface tillage. It is used after ploughing for breaking up and smoothing out the surface of the soil. The purpose of harrowing is to break up clods and to provide a soil structure, called tilth, that is suitable for planting seeds. Coarser harrowing may also be used to remove weeds and to cover seed after sowing. In modern practice they are almost always tractor-mounted implements, either trailed after the tractor by a drawbar or mounted on the three-point hitch. There are four general types of harrows: disc harrows, tine harrows (including spring-tooth harrows, drag harrows, and spike harrows), chain harrows, and chain-disk harrows. Generally a farmer will use two harrows, one after the other. The disk harrow is used first to slice up the large clods left by the mould-board plough, followed by the spring-tooth harrow. To save time and fuel they may be pulled by one tractor; the disk hitched to the tractor, and the spring-tooth hitched to, and directly behind, the disk. The result is a smooth field with powdery dirt at the surface."
    },
    {
        name: "Roller",
        imageUrl: "/static/images/FarmingTools/roller.jpg",
        description: "The roller is an agricultural tool used for flattening land or breaking up large clumps of soil, especially after ploughing or disc harrowing. Rollers prepare optimal seedbeds by making them as flat as is practical and moderately firmed. Flatness is important at planting because it is the only practical way to control average seed planting depth without laborious hand planting of each seed; it is not practical to follow an instruction of (for example) 1-cm planting depth if the contour of the seedbed varies by 2 cm or more between adjacent spots. This is why breaking up of even small clods/lumps, and well-leveled spreading of soil, is important at planting time. Typically, rollers are pulled by tractors or, prior to mechanisation, a team of animals such as horses or oxen. As well as for agricultural purposes, rollers are used on cricket pitches and residential lawn areas. Flatter land makes subsequent weed control and harvesting easier, and rolling can help to reduce moisture loss from cultivated soil. On lawns, rolling levels the land for mowing and compacts the soil surface. Rollers may be weighted in different ways. For many uses a heavy roller is used. These may consist of one or more cylinders made of thick steel, a thinner steel cylinder filled with concrete, or a cylinder filled with water. A water-filled roller has the advantage that the water may be drained out for lighter use or for transport. In frost-prone areas a water filled roller must be drained for winter storage to avoid breakage due to the expansion for water as it turns to ice."
    },
    {
        name: "Cultivator",
        imageUrl: "/static/images/FarmingTools/cultivator.jpg",
        description: "A cultivator is a piece of agricultural equipment used for secondary tillage. One sense of the name refers to frames with teeth (also called shanks) that pierce the soil as they are dragged through it linearly. It also refers to machines that use rotary motion of disks or teeth to accomplish a similar result. The rotary tiller is a principal example. Cultivators stir and pulverize the soil, either before planting (to aerate the soil and prepare a smooth, loose seedbed) or after the crop has begun growing (to kill weeds—controlled disturbance of the topsoil close to the crop plants kills the surrounding weeds by uprooting them, burying their leaves to disrupt their photosynthesis, or a combination of both). Unlike a harrow, which disturbs the entire surface of the soil, cultivators are designed to disturb the soil in careful patterns, sparing the crop plants but disrupting the weeds."
    },
    {
        name: "Billhook",
        imageUrl: "/static/images/FarmingTools/billhook.jpg",
        description: "A billhook or bill hook, also called a pruning knife or spar hook, is a versatile cutting tool used widely in agriculture and forestry for cutting woody material such as shrubs, small trees and branches. The blade is usually made from a medium-carbon steel in varying weights and lengths, but typically 20 to 25 centimetres long. Blades are straight near the handle but have an increasingly strong curve towards the end. The blade is generally sharpened only on the inside of the curve, but double-edged billhooks, or \"broom hooks\", also have a straight secondary edge on the back. The use of a billhook is between that of a knife and an axe. It is often used for cutting woody plants such as saplings and small branches, for hedging and for snedding (stripping the side shoots from a branch). In France and Italy it is widely used for pruning grape vines."
    },
    {
        name: "Secateurs",
        imageUrl: "/static/images/FarmingTools/secateurs.jpg",
        description: "Pruning shears, also called hand pruners (in American English), or Secateurs (in British English), are a type of scissors for use on plants. They are strong enough to prune hard branches of trees and shrubs, sometimes up to two centimetres thick. They are used in gardening, arboriculture, plant nursery works, farming, flower arranging, and nature conservation, where fine-scale habitat management is required. Secateurs have short handles and are operated with one hand.[4] A spring between the handles causes the jaws to open again after closing. When not in use, the jaws may be held closed by a safety catch or by a loop holding the handles together. "
    },
    {
        name: "Grass%20shear",
        imageUrl: "/static/images/FarmingTools/Grass-shear.jpg",
        description: "Grass shears differ from pruning shears in being long-handled and having the handles at right-angles to the blades. They can be used to cut grass from a standing position. Two kinds are available: with the blades horizontal and with the blades vertical. Horizontal blades are used to remove grass which has not been cut by the lawn mower, while vertical blades are used for trimming the edges of a lawn.In 1939, a version of the vertical grass shears was invented having a long handle with a lever at the top, and wheels at the bottom with the shears. This enabled the user to trim the edge of the grass near the sidewalk and driveway. Powered trimmers have for all practical purposes replaced this type of grass shears."
    },
    {
        name: "Hedge%20Trimmer",
        imageUrl: "/static/images/FarmingTools/hedge-trimmer.jpeg",
        description: "A hedge trimmer, shrub trimmer, or bush trimmer is a gardening tool or machine used for trimming (cutting, pruning) hedges or solitary shrubs (bushes). Different designs as well as manual and powered versions of hedge trimmers exist. Hedge trimmers vary between small hand-held devices to larger trimmers mounted on tractors. Manual hedge trimmers (sometimes also called hedge shears or hedge clippers) are designed as large scissors or large pruning shears. They do not need anything to operate and are cheapest/most environmentally friendly. Whereas Motorized hedge trimmers allow work to be done faster and with less effort than manual ones. Their cutting mechanism is similar to that of finger-bar mowers. Powered trimmers are generally designed with safety devices such that they work only when both of the operator's hands are on the handles."
    },
    {
        name: "Rake",
        imageUrl: "/static/images/FarmingTools/rake.jpg",
        description: "A rake is a broom for outside use; a horticultural implement consisting of a toothed bar fixed transversely to a handle, or tines fixed to a handle, and used to collect leaves, hay, grass, etc., and in gardening, for loosening the soil, light weeding and levelling, removing dead grass from lawns, and generally for purposes performed in agriculture by the harrow. Large mechanized versions of rakes are used in farming, called hay rakes, are built in many different forms (e.g. star-wheel rakes, rotary rakes, etc.). Nonmechanized farming may be done with various forms of a hand rake. Modern hand-rakes usually have steel, plastic, or bamboo teeth or tines, though historically they have been made with wood or iron. The handle is typically a ~1.5 metres (5 ft) haft made of wood, bamboo, steel or fiberglass. Leaf rakes, used like a broom to gather leaves, cut grass and debris, have long, flat teeth bent into an L-shape and fanned out from the point of attachment. This permits some flexibility to allow the teeth to conform to terrain, while also being light to minimise damage to vegetation. Compact, telescoping leaf rakes allow the teeth to be withdrawn by sliding a movable fixture point up the shaft. Garden rakes typically have steel teeth and are intended for heavier use in soil and larger debris. They have long, stiff teeth which must be able to withstand abrasion and bending forces. Bow rakes are a subset of garden rakes which separate the handle and bar with a bow-shaped extension which allows the flat back of the bar to be used for levelling and scraping. These may have somewhat finer and shorter teeth and can perform a myriad of gardening and landscape tasks, and due to their more costly construction are likely to be a professional tool. Alternatively, a second set of differently shaped teeth may be added to the back of the bar."
    },
    {
        name: "Khurpa",
        imageUrl: "/static/images/FarmingTools/khurpa.jpg",
        description: "A khurpa is a short handled cutting tool similar to a Trowel with a flat blade used for digging soil and weeding in small gardens or vegetable farms. It is commonly use in small farms or in ridges or rows of vegetables to hoewing or earth up the weeds. It is traditionally used while in a squatting posture. The work khurpa is word of Punjabi language. It is in Punjab and other areas in India for various processes like tilling, bed preparation, weeding and digging at small scale." 
    },
    {
        name: "Sprayer",
        imageUrl: "/static/images/FarmingTools/sprayer.jpg",
        description: "A sprayer is a device used to spray a liquid, where sprayers are commonly used for projection of water, weed killers, crop performance materials, pest maintenance chemicals, as well as manufacturing and production line ingredients. In agriculture, a sprayer is a piece of equipment that is used to apply herbicides, pesticides, and fertilizers on agricultural crops. Sprayers range in size from man-portable units (typically backpacks with spray guns) to trailed sprayers that are connected to a tractor, to self-propelled units similar to tractors with boom mounts of 4–30 feet (1.2–9.1 m) up to 60–151 feet (18–46 m) in length depending on engineering design for tractor and land size. "
    },
    {
        name: "Watering%20Can",
        imageUrl: "/static/images/FarmingTools/watering-can.jpg",
        description: "A watering can (or watering pot) is a portable container, usually with a handle and a funnel, used to water plants by hand. It has been in use since at least A.D. 79 and has since seen many improvements in design. Apart from watering plants, it has varied uses, as it is a fairly versatile tool. The capacity of the container can be anywhere from 0.5 litres (for indoor household plants) to 10 litres (for general garden use). It is usually made of metal, ceramic or plastic. At the end of the spout, a \"rose\" (a device, like a cap, with small holes) can be placed to break up the stream of water into droplets, to avoid excessive water pressure on the soil or on delicate plants. Watering cans are used by gardeners for watering plants, by road workers to apply bitumen to asphalt, as ornaments, and regularly in symbolic art pieces."
    },
    {
        name: "Saw",
        imageUrl: "/static/images/FarmingTools/saw.jpg",
        description: "A saw is a tool consisting of a tough blade, wire, or chain with a hard toothed edge. It is used to cut through material, very often wood, though sometimes metal or stone. The cut is made by placing the toothed edge against the material and moving it forcefully forth and less vigorously back or continuously forward. This force may be applied by hand, or powered by steam, water, electricity or other power source. An abrasive saw has a powered circular blade designed to cut through metal or ceramic."
    },
    {
        name: "Wheelbarrow",
        imageUrl: "/static/images/FarmingTools/wheelbarrow.jpg",
        description: "A wheelbarrow is a small hand-propelled vehicle, usually with just one wheel, designed to be pushed and guided by a single person using two handles at the rear, or by a sail to push the ancient wheelbarrow by wind. The term \"wheelbarrow\" is made of two words: \"wheel\" and \"barrow.\" \"Barrow\" is a derivation of the Old English \"barew\" which was a device used for carrying loads. The wheelbarrow is designed to distribute the weight of its load between the wheel and the operator, so enabling the convenient carriage of heavier and bulkier loads than would be possible were the weight carried entirely by the operator. A two-wheel type is more stable on level ground, while the almost universal one-wheel type has better maneuverability in small spaces, on planks, in water, or when tilted ground would throw the load off balance. The use of one wheel also permits greater control of the deposition of the load upon emptying."
    },
    {
        name: "Hand%20Cultivator",
        imageUrl: "/static/images/FarmingTools/hand-cultivator.jpg",
        description: "Hand cultivators are small, handheld gardening tools that are suitable for digging and breaking up the soil from the depth. It can be helpful for you to loosen the soil and remove weeds without putting much strain on your back and arms. Cultivators can also be used to dig the rows in small vegetables and flower gardens. This is an appropriate tool because it assists in making a better garden that will produce more crops. According to Midwest Gardening cultivating has many benefits. They state that cultivating allows easier penetration of air, nutrients and water into the sun and wind dried soil. Cultivating also remove weeds that steal water and nutrients from the plants. Less supplemental watering is also a benefit gained from cultivating. By using a plastic tool, there is the benefit of the tool never rusting and allows for easy cleaning."
    },
    {
        name: "Hori%20hori",
        imageUrl: "/static/images/FarmingTools/hori-hori.jpg",
        description: "A hori-hori, sometimes referred to as a \"soil knife\" or a \"weeding knife\", is a heavy serrated multi-purpose steel blade for gardening jobs such as digging or cutting. The blade is sharp on both sides and comes to a semi-sharp point at the end. The hori-hori digging tool, first implemented in Japan, was originally used for carefully excavating plants such as Sansai in the mountains. The size of the knife varies from eleven to fifteen inches in total length, depending on the size of the handle. The size of the blade can vary, but it is normally around 67⁄8” × 13⁄4”. The hori-hori has uses in gardening such as weeding, cutting roots, transplanting, removing plants, sod cutting, and splitting perennials. The blade is made of carbon or stainless steel that is concave shaped to make it ideal for digging and prying. The blade has a large smooth wooden handle for comfortable use with one hand. It can serve as a small hand axe."
    },
    {
        name: "Grafting%20Knife",
        imageUrl: "/static/images/FarmingTools/grafting-knife.jpg",
        description: "A sharp knife is essential if you want to have good grafting results. Unlike other knives, grafting knives have thin, sharp, razor-like blades that are beveled on only one side to let the knife cut easily through tough, woody material with a flat cut that provides the most contact possible in the finished graft. While it can be costly, a grafting knife is a wise investment if you do a lot of propagation work. To use a grafting knife, hold it lightly in your hand and rest your thumb along the back of the knife where the handle meets the blade for the most control. Only hold the knife as firmly as required for the job at hand. To cut across small branches, cut in the center of the blade. To make larger cuts, pull the branch closer to the handle to give yourself more leverage."
    },
    {
        name: "Budding%20Knife",
        imageUrl: "/static/images/FarmingTools/budding-knife.jpg",
        description: "A budding knife is the tool used by horticulturist to create a budding or graft union in plants. We sometimes use it in the floristry industry because it is a precision tool and is safer to use than the knife. This is because the budding knife is only sharpened on one side, also meaning that comes in both left and right handed tools. As the budding knife is only sharpened on one side the flat side of the knife that is not sharpened should be held towards the stem that you are cutting and the knife is drawn away from you in a scissor like action with the plant material on the other side. The Budding Knife is used in place of the red and white cutters when creating a floral arrangement. It has the advantage over scissors or cutters as it does not need to be returned to the bench with each use and can be kept in the hand as working on your arrangement. This means that you can work faster once you have mastered it use. The Budding Knife should always be stored closed and placed in your toolbox. You should never store your budding knife open as this is likely to lead to cuts or injuries."
    },
    {
        name: "Garden%20Fork",
        imageUrl: "/static/images/FarmingTools/garden-fork.jpg",
        description: "A garden fork, spading fork, or digging fork is a gardening implement, with a handle and a square-shouldered head featuring several (usually four) short, sturdy tines. It is used for loosening, lifting and turning over soil in gardening and farming, and not to be confused with the pitchfork, a similar tined tool used for moving (or throwing) loose materials such as hay, straw, silage, and manure. A garden fork is used similarly to a spade in loosening and turning over soil. Its tines allow it to be pushed more easily into the ground, and it can rake out stones and weeds and break up clods, it is not so easily stopped by stones, and it does not cut through weed roots or root-crops. Garden forks were originally made of wood, but the majority are now made of forged carbon steel or stainless steel. A smaller version of such forks with shorter, closer-spaced, thinner tines (but a full-sized handle) is known as a border fork or ladies' fork, and is used for lighter work, such as weeding amongst other plants. Forks with broader, flatter tines are made for lifting potatoes and other root crops from the ground. A pair of forks back-to-back may used to lever apart dense clumps of roots."
    }
]